### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by uDEV2019**
german translation

### CODE REVIEW

**Comment by warren-bank** [comment]
Over the past few days, I wrote [tooling](https://github.com/warren-bank/node-translate-android-strings) to automatically generate string translations to all languages supported by the [IBM Cloud](https://github.com/warren-bank/node-ibm-watson-language-translator/blob/master/.etc/docs/IBM-Cloud-account.md) Language Translator service.

I understand that computer generated translations are never perfect, but my aim isn't production-level quality.. only that it's sufficiently usable. How does [this German translation](https://github.com/warren-bank/Android-WebMonkey/blob/master/android-studio-project/WebMonkey/src/main/res/values-de/strings.xml) look? Is it understandable, or mostly gibberish?

**Comment by uDEV2019** [comment]
Gibberish i would say to:
- pref_homepage_array_names_1

not perfect, but acceptable:
- menu_update_scripts
- pref_homepage_array_names_3
- pref_homepage_array_names_4
- pref_updateinterval_title

For german it is better to name "Script" = "Skript" and majority "Scripts" = "Skripte"

**Comment by warren-bank** [comment]
I did some selective copy/paste to apply your updates. Does [this](https://github.com/warren-bank/Android-WebMonkey/blob/master/android-studio-project/WebMonkey/src/main/res/values-de/strings.xml) look right?

**Comment by uDEV2019** [comment]
Only one fix for wrong lower case:
- pref_homepage_array_names_3

Instead of "entwickler" it must be "Entwickler".

**Comment by warren-bank** [comment]
Fixed.. thanks again for the help :smiley:

**Pull request closed without merging**
